INFO: true
logging:
  file:
    name: log.txt
  level:
    in:
      ashokit: DEBUG
  pattern:
    console: '%30c %r [%t]  %p  %m %d  %L %F %n'
    file: '%c %r %t  %p  %m %d  %n '
server:
  port: 1111
spring:
  application:
    name: STOCK-PRICE
  datasource:
    password: Vij@y0301
    url: jdbc:mysql://localhost:3306/MySecondDB
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
